create table customer (
    customer_id varchar(32) primary key,
    full_name varchar(255) not null,
    customer_type varchar(32) not null check (customer_type in ('CUSTOMER','BENEFICIARY')),
    mobile_number varchar(32),
    email varchar(255),
    bank_code varchar(16),
    bank_name varchar(255),
    saved_beneficiary boolean not null default false,
    status varchar(32) not null check (status in ('ACTIVE','DORMANT','FROZEN','CLOSED','RESTRICTED')),
    created_at timestamp not null default current_timestamp
);

create table savings_account (
    account_number varchar(32) primary key,
    customer_id varchar(32) not null references customer(customer_id),
    account_name varchar(255) not null,
    account_alias varchar(255) not null,
    currency varchar(3) not null,
    available_balance numeric(19,2) not null check (available_balance >= 0),
    status varchar(32) not null check (status in ('ACTIVE','DORMANT','FROZEN','CLOSED','RESTRICTED')),
    branch_code varchar(16),
    version bigint not null default 0,
    created_at timestamp not null default current_timestamp
);

create table fund_transfer (
    transaction_id bigint generated by default as identity primary key,
    uuid varchar(64) not null unique,
    source_account varchar(32) not null references savings_account(account_number),
    destination_account varchar(32) not null references savings_account(account_number),
    amount numeric(19,2) not null check (amount > 0),
    currency varchar(3) not null,
    receiver_name varchar(255) not null,
    receiver_bank varchar(16) not null,
    receiver_branch varchar(16),
    narration varchar(255),
    status varchar(32) not null check (status in ('COMPLETED','FAILED','REJECTED')),
    failure_reason varchar(512),
    created_at timestamp not null default current_timestamp,
    completed_at timestamp
);

create index idx_customer_saved_beneficiary on customer(saved_beneficiary, customer_type, status);
create index idx_savings_account_customer on savings_account(customer_id);
create index idx_savings_account_alias on savings_account(account_alias);
create index idx_fund_transfer_uuid on fund_transfer(uuid);
create index idx_fund_transfer_created_at on fund_transfer(created_at);
